# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-xslview}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Albert Lash"]
  s.date = %q{2010-02-13}
  s.description = %q{Simple helper function to render XML via an XSL stylesheet.}
  s.email = %q{albert.lash@docunext.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "README.markdown"
  ]
  s.files = [
    "LICENSE",
     "README",
     "README.markdown",
     "Rakefile",
     "lib/sinatra/xslview.rb",
     "sinatra-xslview.gemspec"
  ]
  s.homepage = %q{http://www.docunext.com/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{XSL Sinatra Helper}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

